
import "./globals.css";
import * as React from "react";
import { Theme } from "../components/theme";
import { AuthUserProvider } from "../../firebase/auth";


export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body>
				<AuthUserProvider>
				<Theme>
          {children}
        </Theme>
				</AuthUserProvider>
			</body>
		</html>
	);
}
